source "https://rubygems.org"

ruby File.read(File.join(__dir__, ".ruby-version")).strip

gem "bundler", "~> 2.5"

# Fastlane is intentionally not added yet — there is no Fastlane lane in
# this repository. It will be added once there's an actual release
# pipeline to automate. See docs/adr/0002-toolchain-baseline.md.
#
# CocoaPods is not added here: apps/mobile/Gemfile (generated by the RN
# CLI template in Step 2) already pins it, with version exclusions for
# known-broken CocoaPods/activesupport/xcodeproj releases. Run
# `bundle install`/`bundle exec pod install` from apps/mobile, not the
# repo root, for iOS native dependency work.
